### ISSUE TITLE
card object has no attribute

### ISSUE THREAD

**Issue by Jing-92** [zjosua/print-as-flashcards#2]
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-06-03 14:11:32

Caught exception:
Traceback (most recent call last):
  File "C:\Users\apple\AppData\Roaming\Anki2\addons21\1672412966\main.py", line 80, in onPrint
    q = esc(c._getQA(True, False)['a']).split('<hr id=answer>')[0]
AttributeError: 'Card' object has no attribute '_getQA'

**Comment by Kaschaaa** [comment]
Same here! Please help :)

Debuginformationen:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-07-21 13:06:20

Caught exception:
Traceback (most recent call last):
  File "C:\Users\NAME\AppData\Roaming\Anki2\addons21\1672412966\main.py", line 80, in onPrint
    q = esc(c._getQA(True, False)['a']).split('<hr id=answer'>)[0]
AttributeError: 'Card' object has no attribute '_getQA'
